# Generated by Django 3.2.7 on 2021-09-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_alter_comment_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='timestamp_minutes',
        ),
    ]
