# Generated by Django 3.2.7 on 2021-09-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_remove_comment_timestamp_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp_seconds',
            field=models.CharField(max_length=12),
        ),
    ]
